import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Wrapper from '../components/Wrapper'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FKT Değerlendirmeler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <div className={styles.MainContent}>
          <div className={styles.InnerContent}>
            <h2 className={styles.MainHeader}>FKT Değerlendirme</h2>
            <span>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reprehenderit quasi cumque voluptas tempora, corrupti officia nisi quam quisquam possimus suscipit, eveniet, quae culpa placeat consectetur sapiente blanditiis delectus. Ipsa, voluptatem.</span>
          </div>
        </div>
      </Wrapper>
    </div>
  )
}

export default Home
